### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by subversivo58** [danstiner/rust-u2f#66]
Hello @danstiner 

I tried to install from the repository and the source ... in both cases to no avail

I am not sure what information is relevant to reproduce | inform:

* OS: Mint 19.3 (64bit)
* Rust version: rustc 1.41.0 (5e1a79984 2020-01-27)
* Make version: 4.1
* Bash version: 4.4.20(1)-release
*cURL version: 7.58.0
* build-essential version:  (12.4ubuntu1)
* libc6-dev version: (2.27-3ubuntu1).

Trying to install from the repository as indicated:

```bash
sudo apt install -y curl
curl -s https://packagecloud.io/install/repositories/danstiner/softu2f/script.deb.sh | sudo bash
sudo apt install -y softu2f
systemctl --user start softu2f
```
........

Failde to install:

```bash
localdev@localdev-desktop:~/Downloads/rust-u2f-master/linux$ curl -s https://packagecloud.io/install/repositories/danstiner/softu2f/script.deb.sh | sudo bash
Detected operating system as localdev/tricia.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/danstiner_softu2f.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
localdev@localdev-desktop:~/Downloads/rust-u2f-master/linux$ sudo apt install -y softu2f
Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
E: Impossible to find the softu2f package
```

I tried to compile after finding question #60 ... but without success too:

```bash
cargo build
   Compiling uhid-sys v1.0.0 (/home/localdev/Downloads/rust-u2f-master/linux/uhid-sys)
warning: constant item is never used: `VENDOR_FIRST_COMMAND_CODE`
 --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/constants.rs:4:1
  |
4 | pub(crate) const VENDOR_FIRST_COMMAND_CODE: u8 = 0x40;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: constant item is never used: `VENDOR_LAST_COMMAND_CODE`
 --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/constants.rs:5:1
  |
5 | pub(crate) const VENDOR_LAST_COMMAND_CODE: u8 = 0xbf;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `SW_COMMAND_NOT_ALLOWED`
  --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/constants.rs:10:1
   |
10 | pub(crate) const SW_COMMAND_NOT_ALLOWED: u16 = 0x6986;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `EC_POINT_FORMAT_UNCOMPRESSED`
  --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/constants.rs:23:1
   |
23 | pub(crate) const EC_POINT_FORMAT_UNCOMPRESSED: u8 = 0x04;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `from_bytes`
  --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/public_key.rs:21:5
   |
21 |     pub(crate) fn from_bytes(bytes: &[u8]) -> Result<PublicKey, String> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `as_ec_key`
  --> /home/localdev/Downloads/rust-u2f-master/u2f-core/src/public_key.rs:34:5
   |
34 |     pub(crate) fn as_ec_key(&self) -> &EcKey<Public> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `None`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:80:5
   |
80 |     None,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: variant is never constructed: `InvalidParameter`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:83:5
   |
83 |     InvalidParameter,
   |     ^^^^^^^^^^^^^^^^

warning: variant is never constructed: `InvalidMessageLength`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:84:5
   |
84 |     InvalidMessageLength,
   |     ^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `MessageTimedOut`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:86:5
   |
86 |     MessageTimedOut,
   |     ^^^^^^^^^^^^^^^

warning: variant is never constructed: `CommandRequiresChannelLock`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:88:5
   |
88 |     CommandRequiresChannelLock,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `SyncCommandFailed`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:89:5
   |
89 |     SyncCommandFailed,
   |     ^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `Wink`
   --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/definitions.rs:429:5
    |
429 |     Wink,
    |     ^^^^

warning: field is never read: `timeout`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/protocol_state_machine.rs:34:5
   |
34 |     timeout: Timeout,
   |     ^^^^^^^^^^^^^^^^

warning: method is never used: `get_ref`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:38:5
   |
38 |     pub fn get_ref(&self) -> &S {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `get_mut`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:43:5
   |
43 |     pub fn get_mut(&mut self) -> &mut S {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `poll_ready`
  --> /home/localdev/Downloads/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:47:5
   |
47 |     pub fn poll_ready(&mut self) -> Async<()> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: failed to run custom build command for `uhid-sys v1.0.0 (/home/localdev/Downloads/rust-u2f-master/linux/uhid-sys)`

Caused by:
  process didn't exit successfully: `/home/localdev/Downloads/rust-u2f-master/linux/target/debug/build/uhid-sys-daedcce3a77ab429/build-script-build` (exit code: 101)
--- stderr
/usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found
/usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Makefile:10: recipe for target 'build' failed
make: *** [build] Error 101
```

Do you have any idea what's going on? Thank you very much in advance

**Comment by danstiner** [comment]
Hi Lauro, thanks for the detailed issue.

The immediate issue is that some headers aren't being found when compiling some bindings. I'm not sure why that would be and chasing down missing headers can be quite annoying, however, I just did a dockerized build on mint 19.3 and it succeeded after installing the packages listed in https://github.com/danstiner/rust-u2f/blob/master/Dockerfile.debian#L7 so hopefully that solves the issue. I added a note to the readme about getting the right packages installed to build.

Alternatively, I also just published a build for Mint 19.3 amd64, so the packagecloud  install step should actually just work now!

**Comment by subversivo58** [comment]
Hi @danstiner, thanks


Thank you for sharing your library, describing success in using your latest packaging and my brief case tests using WebAuthn


-----


Installing the package through the repository now takes place without fail:



```bash
localdev@localdev-desktop:~/Documentos/Developer/rust-u2f-master/linux$ curl -s https://packagecloud.io/install/repositories/danstiner/softu2f/script.deb.sh | sudo bash
[sudo] senha para localdev:
Detected operating system as LinuxMint/tricia.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/danstiner_softu2f.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
localdev@localdev-desktop:~/Documentos/Developer/rust-u2f-master/linux$ sudo apt install -y softu2f
Lendo listas de pacotes... Pronto
Construindo árvore de dependências
Lendo informação de estado... Pronto
The following additional packages will be installed:
  softu2f-system-daemon softu2f-user-daemon u2f-hidraw-policy
Os NOVOS pacotes a seguir serão instalados:
  softu2f softu2f-system-daemon softu2f-user-daemon u2f-hidraw-policy
0 pacotes atualizados, 4 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
É preciso baixar 1.505 kB de arquivos.
Depois desta operação, 5.235 kB adicionais de espaço em disco serão usados.
Obter:1 https://packagecloud.io/danstiner/softu2f/linuxmint tricia/main amd64 u2f-hidraw-policy amd64 1.0.2-1 [3.964 B]
Obter:2 https://packagecloud.io/danstiner/softu2f/linuxmint tricia/main amd64 softu2f-system-daemon amd64 0.4.0 [601 kB]
Obter:3 https://packagecloud.io/danstiner/softu2f/linuxmint tricia/main amd64 softu2f-user-daemon amd64 0.4.0 [898 kB]
Obter:4 https://packagecloud.io/danstiner/softu2f/linuxmint tricia/main amd64 softu2f all 0.4.0 [2.400 B]
Baixados 1.505 kB em 11s (132 kB/s)
A seleccionar pacote anteriormente não seleccionado u2f-hidraw-policy.
(Lendo banco de dados ... 297202 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../u2f-hidraw-policy_1.0.2-1_amd64.deb ...
A descompactar u2f-hidraw-policy (1.0.2-1) ...
A seleccionar pacote anteriormente não seleccionado softu2f-system-daemon.
A preparar para desempacotar .../softu2f-system-daemon_0.4.0_amd64.deb ...
A descompactar softu2f-system-daemon (0.4.0) ...
A seleccionar pacote anteriormente não seleccionado softu2f-user-daemon.
A preparar para desempacotar .../softu2f-user-daemon_0.4.0_amd64.deb ...
A descompactar softu2f-user-daemon (0.4.0) ...
A seleccionar pacote anteriormente não seleccionado softu2f.
A preparar para desempacotar .../archives/softu2f_0.4.0_all.deb ...
A descompactar softu2f (0.4.0) ...
Configurando u2f-hidraw-policy (1.0.2-1) ...
Configurando softu2f-system-daemon (0.4.0) ...
Created symlink /etc/systemd/system/sockets.target.wants/softu2f.socket → /usr/lib/systemd/system/softu2f.socket.
Configurando softu2f-user-daemon (0.4.0) ...
Configurando softu2f (0.4.0) ...
localdev@localdev-desktop:~/Documentos/Developer/rust-u2f-master/linux$ systemctl --user start softu2f
```

Note: yes, my console is a mix of English and local language (pt-BR)


-----


Some tests with WebAuthn work perfectly with several browsers:


* https://demo.yubico.com
* https://webauthndemo.appspot.com
* https://webauthn.io
* https://localhost (mkcert + nginx + node)


**Chrome prints**:


![Captura de tela de 2020-02-08 20-28-56](https://user-images.githubusercontent.com/6475273/74095022-7466d680-4ac9-11ea-80ac-64bf16423337.png)


![yubico-rust-uf2](https://user-images.githubusercontent.com/6475273/74095023-7df03e80-4ac9-11ea-8680-7e8e36a363c0.png)


![Captura de tela de 2020-02-08 21-19-28](https://user-images.githubusercontent.com/6475273/74095025-8183c580-4ac9-11ea-8c57-2636275b9802.png)



-----



The build still fails even though it has all the dependencies (it seems at the same point yet):



```bash
cargo build
   Compiling uhid-sys v1.0.0 (/home/localdev/Documentos/Developer/rust-u2f-master/linux/uhid-sys)
warning: constant item is never used: `VENDOR_FIRST_COMMAND_CODE`
 --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/constants.rs:4:1
  |
4 | pub(crate) const VENDOR_FIRST_COMMAND_CODE: u8 = 0x40;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: constant item is never used: `VENDOR_LAST_COMMAND_CODE`
 --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/constants.rs:5:1
  |
5 | pub(crate) const VENDOR_LAST_COMMAND_CODE: u8 = 0xbf;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `SW_COMMAND_NOT_ALLOWED`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/constants.rs:10:1
   |
10 | pub(crate) const SW_COMMAND_NOT_ALLOWED: u16 = 0x6986;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant item is never used: `EC_POINT_FORMAT_UNCOMPRESSED`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/constants.rs:23:1
   |
23 | pub(crate) const EC_POINT_FORMAT_UNCOMPRESSED: u8 = 0x04;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `from_bytes`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/public_key.rs:21:5
   |
21 |     pub(crate) fn from_bytes(bytes: &[u8]) -> Result<PublicKey, String> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `as_ec_key`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2f-core/src/public_key.rs:34:5
   |
34 |     pub(crate) fn as_ec_key(&self) -> &EcKey<Public> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `None`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:80:5
   |
80 |     None,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: variant is never constructed: `InvalidParameter`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:83:5
   |
83 |     InvalidParameter,
   |     ^^^^^^^^^^^^^^^^

warning: variant is never constructed: `InvalidMessageLength`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:84:5
   |
84 |     InvalidMessageLength,
   |     ^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `MessageTimedOut`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:86:5
   |
86 |     MessageTimedOut,
   |     ^^^^^^^^^^^^^^^

warning: variant is never constructed: `CommandRequiresChannelLock`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:88:5
   |
88 |     CommandRequiresChannelLock,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `SyncCommandFailed`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:89:5
   |
89 |     SyncCommandFailed,
   |     ^^^^^^^^^^^^^^^^^

warning: variant is never constructed: `Wink`
   --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/definitions.rs:429:5
    |
429 |     Wink,
    |     ^^^^

warning: field is never read: `timeout`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/protocol_state_machine.rs:34:5
   |
34 |     timeout: Timeout,
   |     ^^^^^^^^^^^^^^^^

warning: method is never used: `get_ref`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:38:5
   |
38 |     pub fn get_ref(&self) -> &S {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `get_mut`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:43:5
   |
43 |     pub fn get_mut(&mut self) -> &mut S {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `poll_ready`
  --> /home/localdev/Documentos/Developer/rust-u2f-master/u2fhid-protocol/src/segmenting_sink.rs:47:5
   |
47 |     pub fn poll_ready(&mut self) -> Async<()> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: failed to run custom build command for `uhid-sys v1.0.0 (/home/localdev/Documentos/Developer/rust-u2f-master/linux/uhid-sys)`

Caused by:
  process didn't exit successfully: `/home/localdev/Documentos/Developer/rust-u2f-master/linux/target/debug/build/uhid-sys-daedcce3a77ab429/build-script-build` (exit code: 101)
--- stderr
/usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found
/usr/include/x86_64-linux-gnu/sys/types.h:145:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Makefile:10: recipe for target 'build' failed
make: *** [build] Error 101
```


-----


Once again I would like to thank you for being considerate, thank you very much

**Comment by danstiner** [comment]
Glad it worked for you!
